dist: precise

language: java

install: ant deps
jdk:
  - oraclejdk8
  

before_script:
  - travis_retry composer self-update

script:
  - jdk_switcher use oraclejdk8

install:
  - travis_retry composer install --no-interaction --prefer-dist

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
